<template>
  <div class="home-page">
    <section ref="heroSectionRef" class="home-hero-section" aria-labelledby="home-hero-title">
      <div class="home-hero-backdrop" aria-hidden="true">
        <div class="home-hero-static" />
        <video
          v-if="heroVideoActive"
          ref="heroVideoRef"
          class="home-hero-video"
          :src="HERO_VIDEO_SRC"
          muted
          loop
          playsinline
          disablepictureinpicture
          preload="none"
          aria-hidden="true"
        />
      </div>
      <div class="home-hero-scrim" aria-hidden="true" />
      <div class="container home-hero-foreground">
        <div class="home-hero-panel">
          <div class="home-hero-panel__head">
            <div class="home-hero-panel__intro">
              <p class="home-eyebrow">Interactive atlases</p>
              <h1 id="home-hero-title" class="home-hero-title">
                <span class="home-hero-title__line">Dive into</span>
                <span class="home-hero-title__gradient">Subnautica Interactive Map</span>
              </h1>
            </div>
            <p class="home-hero-meta">Fan site · Two live atlases · Guides soon</p>
          </div>
          <div class="home-hero-lead">
            <p>
              This site wraps a MapLibre-powered atlas for the original <em>Subnautica</em> and a separate build for
              <em>Subnautica: Below Zero</em>: biome polygons, region labels, resource and POI pins, opacity sliders for
              the base raster and cave sheet, and the usual pan–zoom gestures you expect from a desktop-grade map.
            </p>
            <p>
              Marker text and media are bundled with the site (or generated by the repo’s scripts) so you can browse
              without hopping through ad-heavy wikis. A third slot is reserved for <em>Subnautica&nbsp;2</em> when a
              stable public dataset exists; until then it links to a short status page only.
            </p>
          </div>

          <div class="home-hero-maprow" role="list" aria-label="Map entry points">
            <RouterLink
              class="home-mapslot home-mapslot--sn1"
              to="/maps/subnautica"
              role="listitem"
              aria-label="Open the Subnautica full-screen map"
            >
              <div class="home-mapslot__thumb">
                <img
                  src="/images/hero-01.webp"
                  alt=""
                  decoding="async"
                  fetchpriority="high"
                />
              </div>
              <div class="home-mapslot__body">
                <h2 class="home-mapslot__title">Subnautica Map</h2>
                <p class="home-mapslot__desc">Crash site 4546B—biomes, resources, and pins.</p>
                <span class="home-mapslot__action">Open map</span>
              </div>
            </RouterLink>

            <RouterLink
              class="home-mapslot home-mapslot--sn2"
              to="/maps/subnautica-2"
              role="listitem"
              aria-label="Open the Subnautica 2 full-screen interactive map"
            >
              <div class="home-mapslot__thumb">
                <img src="/images/hero-02.webp" alt="" decoding="async" />
              </div>
              <div class="home-mapslot__body">
                <h2 class="home-mapslot__title">Subnautica 2 Map</h2>
                <p class="home-mapslot__desc">Early access world—Map Genie tiles, biomes, and pins.</p>
                <span class="home-mapslot__action">Open map</span>
              </div>
            </RouterLink>

            <RouterLink
              class="home-mapslot home-mapslot--bz"
              to="/maps/subnautica-below-zero"
              role="listitem"
              aria-label="Open the Subnautica Below Zero full-screen map"
            >
              <div class="home-mapslot__thumb">
                <img src="/images/hero-03.webp" alt="" decoding="async" />
              </div>
              <div class="home-mapslot__body">
                <h2 class="home-mapslot__title">Subnautica Below Zero Map</h2>
                <p class="home-mapslot__desc">Ice, shallows, and deeper biomes—own pin set.</p>
                <span class="home-mapslot__action">Open map</span>
              </div>
            </RouterLink>
          </div>
        </div>
      </div>
    </section>

    <section class="home-trailer-section" aria-labelledby="home-trailer-heading">
      <div class="home-trailer-bg" aria-hidden="true" />
      <div class="container">
        <div class="home-trailer-content">
          <div class="home-trailer-split">
            <div class="home-trailer-copy">
              <p class="home-eyebrow home-eyebrow--on-dark">Media</p>
              <h2 id="home-trailer-heading" class="home-section-title">Subnautica 2 trailer</h2>
              <p class="home-trailer-intro">
                Unknown Worlds shares release timing through its own announcements—this page skips a speculative
                countdown so nothing goes stale overnight.
              </p>
              <p class="home-trailer-intro">
                On the right is the official cinematic trailer for Subnautica&nbsp;2 (same embed ID as before). The
                official site describes Subnautica&nbsp;2 as an underwater survival adventure on a new alien world, with
                base building, crafting, exploration—and co-op play as a headline feature.
              </p>
            </div>
            <div class="home-trailer-frame-wrap">
              <div class="home-trailer-frame">
                <iframe
                  v-if="trailerEmbedLoaded"
                  class="home-trailer-frame__embed"
                  :src="trailerEmbedSrc"
                  title="Official Subnautica 2 cinematic trailer (YouTube embed)"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                  allowfullscreen
                />
                <div
                  v-else
                  class="home-trailer-poster"
                  role="presentation"
                >
                  <img
                    class="home-trailer-poster__img"
                    src="/images/video-bg.webp"
                    alt=""
                    decoding="async"
                    fetchpriority="low"
                  />
                  <div class="home-trailer-poster__scrim" aria-hidden="true" />
                  <button
                    type="button"
                    class="home-trailer-poster__play"
                    aria-label="Load and play the official Subnautica 2 cinematic trailer"
                    @click="trailerEmbedLoaded = true"
                  >
                    <svg
                      class="home-trailer-poster__play-icon"
                      viewBox="0 0 88 88"
                      width="88"
                      height="88"
                      aria-hidden="true"
                      focusable="false"
                    >
                      <circle cx="44" cy="44" r="40" fill="rgba(4, 12, 22, 0.55)" stroke="rgba(46, 243, 217, 0.85)" stroke-width="3" />
                      <circle cx="44" cy="44" r="36" fill="rgba(46, 243, 217, 0.18)" />
                      <path
                        d="M38 30 L38 58 L60 44 Z"
                        fill="var(--color-text)"
                      />
                    </svg>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="home-about-section" aria-labelledby="home-about-heading">
      <div class="container">
        <div class="home-about-head">
          <p class="home-eyebrow">The series</p>
          <h2 id="home-about-heading" class="home-section-title">About Subnautica</h2>
        </div>

        <div class="home-about-top">
          <div class="home-about-top__media">
            <img class="home-about-top__img" src="/images/about-img.webp" alt="" decoding="async" loading="lazy" />
          </div>
          <div class="home-about-top__copy">
            <p>
              <strong>Subnautica</strong> is a single-player, open-world survival action-adventure developed and
              published by Unknown Worlds Entertainment. After its early-access period on Windows, the 1.0 version shipped
              in January&nbsp;2018, with console ports following across that generation.
            </p>
            <p>
              You play a survivor of the starship <em>Aurora</em>, which crash-lands on planet 4546B—an almost entirely
              oceanic world. Gameplay combines free diving, piloting small submersibles, building seabases, scanning
              alien flora and fauna, and following environmental storytelling delivered through abandoned habitats, data
              terminals, and audio logs.
            </p>
            <h3>Core survival loop</h3>
            <p>
              You gather materials from seabed outcrops and life forms, convert them into tools, oxygen upgrades, and
              vehicles such as the Seamoth, PRAWN suit, and Cyclops submarine, then push outward into hotter biomes,
              deeper caves, and story-critical facilities. Pressure, temperature, and hostile wildlife—not a traditional
              hunger meter alone—create most of the tension.
            </p>
            <h3>Subnautica: Below Zero</h3>
            <p>
              <strong>Subnautica: Below Zero</strong> is a standalone follow-up set on the same planet but focused on a
              new protagonist exploring polar regions above and below the ice. The 1.0 PC release arrived in
              May&nbsp;2021, again from Unknown Worlds Entertainment.
            </p>
            <h3>Subnautica 2</h3>
            <p>
              Unknown Worlds Entertainment positions <strong>Subnautica&nbsp;2</strong> as the next major installment—an
              underwater survival adventure on a new world, with four-player co-op among the features highlighted on
              the official site. Treat anything beyond first-party materials as unconfirmed.
            </p>
            <h3>How this fan site fits in</h3>
            <p>
              <strong>Subnautica Map</strong> is an unofficial companion: interactive maps now, structured guides later.
              It does not redistribute the commercial game—only map tiles and marker data in this build, plus original
              copy on these pages.
            </p>
          </div>
        </div>

        <div class="home-about-pillars" aria-label="Site pillars">
          <div class="home-about-card">
            <span class="home-about-card__label">Explore</span>
            <p class="home-about-card__text">Pan across biome polygons and POI layers tuned for each game’s dataset.</p>
          </div>
          <div class="home-about-card home-about-card--coral">
            <span class="home-about-card__label">Adapt</span>
            <p class="home-about-card__text">Opacity sliders and cave toggles behave like a helm HUD you can dial in.</p>
          </div>
          <div class="home-about-card home-about-card--sun">
            <span class="home-about-card__label">Survive</span>
            <p class="home-about-card__text">Use pins as planning aids—oxygen, routing, and risk are still on you.</p>
          </div>
        </div>
      </div>
    </section>

    <section class="home-faq-section" aria-labelledby="home-faq-heading">
      <div class="container">
        <div class="home-faq-head">
          <p class="home-eyebrow">Support</p>
          <h2 id="home-faq-heading" class="home-section-title">FAQ</h2>
        </div>
        <div class="home-faq-list">
          <article class="home-faq-row">
            <h3 class="home-faq-row__q">Is Subnautica 2 multiplayer?</h3>
            <p class="home-faq-row__a">
              Yes—Unknown Worlds advertises <strong>Subnautica&nbsp;2</strong> with <strong>up to four-player
              co-op</strong> on the official site. That is separate from the original <em>Subnautica</em> and
              <em>Below Zero</em>, which shipped as single-player games in their official versions.
            </p>
          </article>
          <article class="home-faq-row">
            <h3 class="home-faq-row__q">What are the Aurora door codes?</h3>
            <p class="home-faq-row__a">
              In the first <em>Subnautica</em>, the numbered keypads on the Aurora commonly use these codes (spoiler):
              <strong>2679</strong> (Captain’s Quarters), <strong>1454</strong> (Cargo Bay),
              <strong>1869</strong> (Cabin / locker area), and <strong>6483</strong> (lab access in many community
              references). You typically find hints on PDAs and posters before you reach each door—enter once and the
              door stays open for that save.
            </p>
          </article>
          <article class="home-faq-row">
            <h3 class="home-faq-row__q">How to play Subnautica coop?</h3>
            <p class="home-faq-row__a">
              <em>Subnautica</em> and <em>Below Zero</em> do not ship with official online co-op; players use
              community projects such as <strong>Nitrox</strong> (third-party mod + client) to play the first game
              together—install steps and compatibility change with game patches, so follow that project’s current docs.
              For <em>Subnautica&nbsp;2</em>, co-op is part of the product design from Unknown Worlds; use their official
              channels for how access works in each release phase.
            </p>
          </article>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { nextTick, onMounted, onUnmounted, ref } from 'vue'

/** 背景视频（文件放在 public/video/5KOrADaW.mp4） */
const HERO_VIDEO_SRC = '/video/5KOrADaW.mp4'

/** 首页预告片：点击后再加载 iframe，减少第三方请求与首屏重量 */
const TRAILER_EMBED_BASE = 'https://www.youtube.com/embed/8EZhCzFaQuw'
const trailerEmbedLoaded = ref(false)
const trailerEmbedSrc = `${TRAILER_EMBED_BASE}?autoplay=1&rel=0`

const heroSectionRef = ref(null)
const heroVideoRef = ref(null)
const heroVideoActive = ref(false)

/** @type {IntersectionObserver | null} */
let heroVideoIo = null
/** @type {(() => void) | null} */
let heroVisHandler = null

function shouldLoadHeroVideo() {
  if (typeof window === 'undefined') return false
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return false
  const c = navigator.connection || navigator.mozConnection || navigator.webkitConnection
  if (c?.saveData) return false
  const t = c?.effectiveType
  if (t === 'slow-2g' || t === '2g') return false
  return true
}

function isHeroInView(root) {
  const r = root.getBoundingClientRect()
  return r.bottom > -64 && r.top < window.innerHeight + 64
}

onMounted(async () => {
  heroVideoActive.value = shouldLoadHeroVideo()
  await nextTick()
  if (!heroVideoActive.value) return

  const root = heroSectionRef.value
  const video = heroVideoRef.value
  if (!root || !video) return

  video.muted = true
  video.defaultMuted = true
  video.playsInline = true
  video.loop = true
  video.preload = 'none'

  const startBufferAndPlay = () => {
    if (video.preload !== 'auto') {
      video.preload = 'auto'
      video.load()
    }
    video.play().catch(() => {})
  }

  heroVideoIo = new IntersectionObserver(
    (entries) => {
      for (const e of entries) {
        if (e.isIntersecting && isHeroInView(root)) startBufferAndPlay()
        else video.pause()
      }
    },
    { root: null, rootMargin: '72px 0px', threshold: 0.05 },
  )
  heroVideoIo.observe(root)

  heroVisHandler = () => {
    if (document.visibilityState === 'hidden') {
      video.pause()
      return
    }
    if (isHeroInView(root)) startBufferAndPlay()
  }
  document.addEventListener('visibilitychange', heroVisHandler)
})

onUnmounted(() => {
  if (heroVisHandler) {
    document.removeEventListener('visibilitychange', heroVisHandler)
    heroVisHandler = null
  }
  heroVideoIo?.disconnect()
  heroVideoIo = null
  const video = heroVideoRef.value
  if (video) {
    try {
      video.pause()
      video.removeAttribute('src')
      video.load()
    } catch {
      /* ignore */
    }
  }
})
</script>

<style scoped>
.home-page {
  padding-bottom: 4rem;
}

/* —— Hero：背景视频 + 压暗层 + 前景玻璃面板（视频仅视口内缓冲/播放） —— */
.home-hero-section {
  position: relative;
  padding-block: 5rem;
  overflow: hidden;
}

.home-hero-backdrop {
  position: absolute;
  inset: 0;
  z-index: 0;
  pointer-events: none;
}

.home-hero-static {
  position: absolute;
  inset: 0;
  background:
    radial-gradient(ellipse 85% 55% at 50% 0%, rgba(46, 243, 217, 0.12), transparent 52%),
    radial-gradient(ellipse 45% 38% at 100% 70%, rgba(255, 94, 200, 0.08), transparent 50%),
    linear-gradient(165deg, #061525 0%, #030810 55%, #020408 100%);
}

.home-hero-video {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
  object-position: center 40%;
  /* 限制缩放计算量：仅 Hero 区域尺寸 */
  transform: translateZ(0);
}

.home-hero-scrim {
  position: absolute;
  inset: 0;
  z-index: 1;
  pointer-events: none;
  background: linear-gradient(
    180deg,
    rgba(2, 6, 12, 0.38) 0%,
    rgba(4, 12, 22, 0.52) 45%,
    rgba(2, 5, 10, 0.62) 100%
  );
}

.home-hero-foreground {
  position: relative;
  z-index: 2;
}

.home-hero-panel {
  position: relative;
  padding: 1.85rem;
  border-radius: 22px;
  background: linear-gradient(155deg, rgba(12, 32, 52, 0.42) 0%, rgba(4, 12, 22, 0.5) 100%);
  border: 1px solid rgba(124, 245, 255, 0.28);
  box-shadow:
    0 28px 80px rgba(0, 0, 0, 0.35),
    inset 0 1px 0 rgba(255, 255, 255, 0.08);
  backdrop-filter: blur(10px);
}

.home-hero-panel__head {
  display: flex;
  flex-wrap: wrap;
  align-items: flex-end;
  justify-content: space-between;
  gap: 0.75rem 1.5rem;
  margin-bottom: 0.65rem;
}

.home-hero-panel__intro {
  min-width: min(100%, 18rem);
}

.home-hero-meta {
  margin: 0;
  font-family: var(--font-display);
  font-size: 0.68rem;
  font-weight: 700;
  letter-spacing: 0.14em;
  text-transform: uppercase;
  color: rgba(210, 244, 252, 0.55);
  text-align: right;
}

.home-eyebrow {
  margin: 0 0 0.65rem;
  font-family: var(--font-display);
  font-size: 0.7rem;
  font-weight: 800;
  letter-spacing: 0.28em;
  text-transform: uppercase;
  color: var(--color-coral);
}

.home-eyebrow--on-dark {
  color: var(--color-sun);
}

.home-hero-title {
  margin: 0 0 0.5rem;
  display: flex;
  flex-direction: column;
  gap: 0.1rem;
}

.home-hero-title__line {
  font-size: 1.12rem;
  font-weight: 600;
  letter-spacing: 0.16em;
  text-transform: uppercase;
  color: var(--color-muted);
}

.home-hero-title__gradient {
  font-size: 3.1rem;
  font-weight: 800;
  letter-spacing: 0.02em;
  line-height: 1.05;
  background: linear-gradient(105deg, var(--color-aqua) 0%, var(--color-ice) 38%, var(--color-sun) 72%, var(--color-coral) 100%);
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
}

.home-hero-lead {
  margin: 0 0 1.25rem;
  max-width: 52rem;
  font-size: 0.98rem;
  color: rgba(232, 250, 255, 0.92);
  line-height: 1.65;
  text-shadow: 0 1px 12px rgba(0, 8, 16, 0.75);
}

.home-hero-lead p {
  margin: 0 0 0.75em;
}

.home-hero-lead p:last-child {
  margin-bottom: 0;
}

.home-hero-maprow {
  display: grid;
  gap: 0.75rem;
  grid-template-columns: 1fr;
}

@media (min-width: 768px) {
  .home-hero-maprow {
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 0.8rem;
  }
}

@media (min-width: 1024px) {
  .home-hero-maprow {
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 0.85rem;
    align-items: stretch;
  }
}

.home-mapslot {
  display: flex;
  flex-direction: row;
  align-items: stretch;
  align-self: stretch;
  min-height: 124px;
  text-decoration: none;
  color: inherit;
  border-radius: 16px;
  overflow: hidden;
  background: rgba(5, 14, 26, 0.92);
  border: 1px solid var(--color-line);
  box-shadow: 0 12px 32px rgba(0, 0, 0, 0.35);
  transition:
    transform 0.2s ease,
    border-color 0.2s ease,
    box-shadow 0.2s ease;
}

.home-mapslot:hover {
  transform: translateY(-3px);
  border-color: rgba(255, 255, 255, 0.28);
  box-shadow: 0 18px 44px rgba(0, 0, 0, 0.45), var(--shadow-glow);
}

.home-mapslot:focus-visible {
  outline: 2px solid var(--color-aqua);
  outline-offset: 3px;
}

.home-mapslot--sn1 {
  border-color: rgba(46, 243, 217, 0.35);
}

.home-mapslot--sn1:hover {
  border-color: rgba(46, 243, 217, 0.75);
}

.home-mapslot--sn2 {
  border-color: rgba(255, 94, 200, 0.4);
  box-shadow: 0 12px 32px rgba(0, 0, 0, 0.35), 0 0 28px rgba(255, 94, 200, 0.1);
}

.home-mapslot--sn2:hover {
  border-color: rgba(255, 94, 200, 0.85);
  box-shadow: 0 18px 44px rgba(0, 0, 0, 0.45), 0 0 40px rgba(255, 94, 200, 0.2);
}

.home-mapslot--bz {
  border-color: rgba(124, 245, 255, 0.35);
}

.home-mapslot--bz:hover {
  border-color: rgba(124, 245, 255, 0.85);
}

.home-mapslot__thumb {
  position: relative;
  flex: 0 0 44%;
  min-width: 132px;
  max-width: 220px;
  align-self: center;
  overflow: hidden;
  background: rgba(0, 0, 0, 0.35);
}

.home-mapslot--sn1 .home-mapslot__thumb,
.home-mapslot--sn2 .home-mapslot__thumb {
  aspect-ratio: 460 / 215;
}

.home-mapslot--bz .home-mapslot__thumb {
  aspect-ratio: 340 / 191;
}

.home-mapslot__thumb img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.home-mapslot__badge {
  position: absolute;
  top: 0.45rem;
  right: 0.45rem;
  padding: 0.2rem 0.5rem;
  font-size: 0.58rem;
  font-weight: 800;
  letter-spacing: 0.14em;
  text-transform: uppercase;
  color: var(--color-void);
  background: var(--color-sun);
  border-radius: 6px;
}

.home-mapslot__body {
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  gap: 0.2rem;
  padding: 0.75rem 0.9rem 0.85rem 0.85rem;
  min-width: 0;
}

.home-mapslot__title {
  margin: 0;
  font-size: 0.95rem;
  font-weight: 800;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--color-aqua);
}

.home-mapslot--sn2 .home-mapslot__title {
  color: var(--color-magenta);
}

.home-mapslot--bz .home-mapslot__title {
  color: var(--color-ice);
}

.home-mapslot:hover .home-mapslot__title {
  color: var(--color-sun);
}

.home-mapslot--sn2:hover .home-mapslot__title {
  color: var(--color-sun);
}

.home-mapslot__desc {
  margin: 0;
  font-size: 0.8rem;
  color: var(--color-muted);
  line-height: 1.45;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.home-mapslot__action {
  margin-top: 0.35rem;
  font-family: var(--font-display);
  font-size: 0.65rem;
  font-weight: 800;
  letter-spacing: 0.16em;
  text-transform: uppercase;
  color: var(--color-coral);
}

.home-mapslot:hover .home-mapslot__action {
  color: var(--color-aqua);
}

/* —— Trailer：左文右视频 —— */
.home-trailer-section {
  position: relative;
  padding-block: 3.5rem;
  margin-top: 0.35rem;
}

.home-trailer-bg {
  position: absolute;
  inset: 0;
  background: linear-gradient(
    135deg,
    rgba(40, 8, 52, 0.55) 0%,
    rgba(6, 40, 52, 0.75) 38%,
    rgba(8, 22, 48, 0.9) 100%
  );
  border-block: 1px solid var(--color-line);
  pointer-events: none;
}

.home-trailer-content {
  position: relative;
}

.home-trailer-split {
  display: grid;
  gap: 1.75rem;
  align-items: stretch;
}

@media (min-width: 1024px) {
  .home-trailer-split {
    grid-template-columns: minmax(0, 0.95fr) minmax(0, 1.05fr);
    gap: 2rem;
  }
}

.home-trailer-copy .home-section-title {
  margin-top: 0;
}

.home-section-title {
  margin: 0 0 0.75rem;
  font-size: 2rem;
  font-weight: 800;
  letter-spacing: 0.03em;
  color: var(--color-text);
}

.home-trailer-intro {
  margin: 0 0 0.85em;
  color: rgba(232, 252, 255, 0.85);
  line-height: 1.6;
  font-size: 0.98rem;
}

.home-trailer-intro:last-of-type {
  margin-bottom: 0;
}

.home-trailer-frame-wrap {
  display: flex;
  align-items: stretch;
  min-height: 0;
}

.home-trailer-frame {
  position: relative;
  flex: 1;
  width: 100%;
  min-height: 200px;
  border-radius: var(--radius-lg);
  overflow: hidden;
  background: #050810;
  border: 3px solid rgba(46, 243, 217, 0.55);
  box-shadow:
    0 0 0 1px rgba(255, 94, 200, 0.35),
    0 24px 60px rgba(0, 0, 0, 0.55),
    inset 0 0 60px rgba(124, 245, 255, 0.06);
  aspect-ratio: 16 / 9;
}

.home-trailer-frame__embed {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  border: 0;
  display: block;
}

.home-trailer-poster {
  position: absolute;
  inset: 0;
  display: grid;
  place-items: center;
}

.home-trailer-poster__img {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
  object-position: center;
}

.home-trailer-poster__scrim {
  position: absolute;
  inset: 0;
  background: linear-gradient(
    180deg,
    rgba(2, 6, 12, 0.35) 0%,
    rgba(4, 12, 22, 0.55) 50%,
    rgba(2, 5, 10, 0.68) 100%
  );
  pointer-events: none;
}

.home-trailer-poster__play {
  position: relative;
  z-index: 1;
  display: grid;
  place-items: center;
  padding: 0;
  margin: 0;
  border: 0;
  border-radius: 999px;
  background: transparent;
  cursor: pointer;
  transition: transform 0.18s ease, filter 0.18s ease;
}

.home-trailer-poster__play:hover {
  transform: scale(1.06);
  filter: drop-shadow(0 0 22px rgba(46, 243, 217, 0.45));
}

.home-trailer-poster__play:focus-visible {
  outline: 2px solid var(--color-aqua);
  outline-offset: 4px;
}

.home-trailer-poster__play:active {
  transform: scale(0.98);
}

.home-trailer-poster__play-icon {
  display: block;
  width: clamp(4.25rem, 12vw, 5.5rem);
  height: auto;
}

/* —— About：上 左图右文，下 三卡横排 —— */
.home-about-section {
  padding-block: 3.75rem;
}

.home-about-head,
.home-faq-head {
  margin-bottom: 1.75rem;
}

.home-about-top {
  display: grid;
  gap: 1.75rem;
  align-items: start;
}

@media (min-width: 1024px) {
  .home-about-top {
    grid-template-columns: minmax(220px, 34%) minmax(0, 1fr);
  }
}

.home-about-top__media {
  border-radius: var(--radius-lg);
  overflow: hidden;
  border: 2px solid var(--color-line);
  box-shadow: 0 20px 48px rgba(0, 0, 0, 0.4);
  background: rgba(6, 18, 32, 0.6);
  aspect-ratio: 658 / 987;
}

.home-about-top__img {
  width: 100%;
  height: 100%;
  display: block;
  object-fit: cover;
}

.home-about-top__copy p:last-child {
  margin-bottom: 0;
}

.home-about-top__copy h3 {
  margin-top: 1.25rem;
  margin-bottom: 0.4em;
  font-size: 0.95rem;
  font-weight: 800;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--color-aqua);
}

.home-about-pillars {
  display: grid;
  gap: 0.85rem;
  margin-top: 2.25rem;
}

@media (min-width: 768px) {
  .home-about-pillars {
    grid-template-columns: repeat(3, minmax(0, 1fr));
  }
}

.home-about-card {
  padding: 1rem 1.1rem;
  border-radius: 14px;
  background: linear-gradient(145deg, rgba(46, 243, 217, 0.12) 0%, rgba(8, 24, 44, 0.9) 100%);
  border: 1px solid rgba(46, 243, 217, 0.35);
}

.home-about-card--coral {
  background: linear-gradient(145deg, rgba(255, 122, 92, 0.15) 0%, rgba(8, 24, 44, 0.9) 100%);
  border-color: rgba(255, 122, 92, 0.4);
}

.home-about-card--sun {
  background: linear-gradient(145deg, rgba(245, 255, 138, 0.14) 0%, rgba(8, 24, 44, 0.9) 100%);
  border-color: rgba(245, 255, 138, 0.35);
}

.home-about-card__label {
  display: block;
  margin-bottom: 0.35rem;
  font-family: var(--font-display);
  font-size: 0.72rem;
  font-weight: 800;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  color: var(--color-sun);
}

.home-about-card__text {
  margin: 0;
  font-size: 0.88rem;
  color: var(--color-muted);
  line-height: 1.55;
}

/* —— FAQ：一行一条 —— */
.home-faq-section {
  padding-block: 3.25rem;
}

.home-faq-list {
  display: flex;
  flex-direction: column;
  gap: 0;
}

.home-faq-row {
  margin: 0;
  padding: 1.35rem 0;
  border-bottom: 1px solid var(--color-line);
}

.home-faq-row:first-child {
  padding-top: 0.35rem;
}

.home-faq-row:last-child {
  border-bottom: none;
  padding-bottom: 0;
}

.home-faq-row__q {
  margin: 0 0 0.5rem;
  font-size: 1.05rem;
  font-weight: 800;
  color: var(--color-coral);
  letter-spacing: 0.02em;
}

.home-faq-row__a {
  margin: 0;
  font-size: 0.95rem;
  color: var(--color-muted);
  line-height: 1.6;
  max-width: 58rem;
}

/* 首页：仅 ≤1023（平板）与 ≤767（移动） */
@media (max-width: 1023px) {
  .home-page {
    padding-bottom: 3rem;
  }

  .home-hero-section {
    padding-block: 3.5rem;
  }

  .home-hero-panel {
    padding: 1.45rem;
    border-radius: 18px;
  }

  .home-hero-title__line {
    font-size: 1.02rem;
  }

  .home-hero-title__gradient {
    font-size: 2.4rem;
  }

  .home-hero-lead {
    font-size: 0.92rem;
    line-height: 1.6;
  }

  .home-section-title {
    font-size: 1.65rem;
  }

  .home-trailer-section {
    padding-block: 2.75rem;
  }

  .home-trailer-split {
    gap: 1.25rem;
  }

  .home-trailer-intro {
    font-size: 0.92rem;
  }

  .home-about-section {
    padding-block: 2.85rem;
  }

  .home-about-head,
  .home-faq-head {
    margin-bottom: 1.35rem;
  }

  .home-about-top {
    gap: 1.25rem;
  }

  .home-about-pillars {
    margin-top: 1.9rem;
  }

  .home-about-card {
    padding: 0.9rem 1rem;
  }

  .home-about-card__text {
    font-size: 0.85rem;
  }

  .home-faq-section {
    padding-block: 2.75rem;
  }

  .home-faq-row {
    padding: 1.15rem 0;
  }

  .home-faq-row__q {
    font-size: 0.98rem;
  }

  .home-faq-row__a {
    font-size: 0.9rem;
  }

  .home-mapslot {
    min-height: 112px;
  }

  .home-mapslot__body {
    padding: 0.65rem 0.75rem;
  }

  .home-mapslot__title {
    font-size: 0.88rem;
  }

  .home-mapslot__desc {
    font-size: 0.76rem;
  }
}

@media (max-width: 767px) {
  .home-page {
    padding-bottom: 2.5rem;
  }

  .home-hero-section {
    padding-block: 2.65rem;
  }

  .home-hero-panel {
    padding: 1.15rem;
    border-radius: 16px;
  }

  .home-hero-panel__head {
    gap: 0.55rem 1rem;
  }

  .home-hero-meta {
    text-align: left;
    width: 100%;
  }

  .home-hero-title__line {
    font-size: 0.92rem;
    letter-spacing: 0.12em;
  }

  .home-hero-title__gradient {
    font-size: 1.92rem;
  }

  .home-eyebrow {
    font-size: 0.64rem;
    letter-spacing: 0.22em;
  }

  .home-hero-lead {
    font-size: 0.88rem;
    margin-bottom: 1rem;
  }

  .home-section-title {
    font-size: 1.38rem;
  }

  .home-trailer-section {
    padding-block: 2.25rem;
  }

  .home-trailer-split {
    gap: 1.1rem;
  }

  .home-trailer-intro {
    font-size: 0.88rem;
  }

  .home-about-section {
    padding-block: 2.35rem;
  }

  .home-about-head,
  .home-faq-head {
    margin-bottom: 1.1rem;
  }

  .home-about-top__copy h3 {
    font-size: 0.88rem;
  }

  .home-about-pillars {
    margin-top: 1.5rem;
    gap: 0.75rem;
  }

  .home-about-card {
    padding: 0.85rem 0.95rem;
  }

  .home-about-card__label {
    font-size: 0.66rem;
  }

  .home-about-card__text {
    font-size: 0.82rem;
  }

  .home-faq-section {
    padding-block: 2.35rem;
  }

  .home-faq-row {
    padding: 1rem 0;
  }

  .home-faq-row__q {
    font-size: 0.92rem;
  }

  .home-faq-row__a {
    font-size: 0.85rem;
  }

  .home-mapslot {
    min-height: 104px;
  }

  .home-mapslot__thumb {
    flex: 0 0 38%;
    min-width: 110px;
    max-width: 165px;
  }

  .home-mapslot__body {
    padding: 0.55rem 0.65rem;
  }

  .home-mapslot__title {
    font-size: 0.82rem;
  }

  .home-mapslot__desc {
    font-size: 0.72rem;
  }
}
</style>
